
# https://taskfile.dev

version: '3'

tasks:
  build:
    vars:
      ANTLR_GENERATED: antlr4cpp_generated
      ANTLR_RUNTIME: /usr/include/antlr4-runtime
      ANTLR_LIB:     /usr/lib/x86_64-linux-gnu
    cmds:
      - mkdir -p {{.ANTLR_GENERATED}} bin && rm -rf {{.ANTLR_GENERATED}}/* bin/*
      - |
        antlr4 -Dlanguage=Cpp -package gitql -visitor -listener \
          -o {{.ANTLR_GENERATED}} \
          TParser.g4 TLexer.g4
      - |
        g++ -std=c++17 \
          -I{{.ANTLR_GENERATED}} \
          -I{{.ANTLR_GENERATED}}/gitql \
          -Iinclude -I{{.ANTLR_RUNTIME}} \
          src/*.cpp {{.ANTLR_GENERATED}}/*.cpp main.cpp \
          -o bin/gitql \
          -L{{.ANTLR_LIB}} -lantlr4-runtime \
          $(pkg-config --libs xapian-core libgit2) \
          -labsl_hash -labsl_raw_hash_set